name: Run Renovate
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Generate App Token
        id: generate-app-token
        uses: actions/create-github-app-token@v1.10.1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.12
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_PLATFORM: "github"
          RENOVATE_PLATFORM_COMMIT: "true"
        with:
          token: "${{ steps.generate-app-token.outputs.token }}"
